In [2]:
# importing necessary library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
# loading the dataset
# The dataset is a CSV file containing tweets labelled with sentiment
data = pd.read_csv('/Users/mac/Downloads/data.csv',encoding='ISO-8859-1')
df = data.copy()

In [18]:
# Displaying the first few rows of the dataset
df.head()

,Date,Label,Top1,Top2,Top3,Top4,Top5,Top6,Top7,Top8,...,Top16,Top17,Top18,Top19,Top20,Top21,Top22,Top23,Top24,Top25
0,2000-01-03,0,A 'hindrance to operations': extracts from the...,Scorecard,Hughes' instant hit buoys Blues,Jack gets his skates on at ice-cold Alex,Chaos as Maracana builds up for United,Depleted Leicester prevail as Elliott spoils E...,Hungry Spurs sense rich pickings,Gunners so wide of an easy target,...,Flintoff injury piles on woe for England,Hunters threaten Jospin with new battle of the...,Kohl's successor drawn into scandal,The difference between men and women,"Sara Denver, nurse turned solicitor",Diana's landmine crusade put Tories in a panic,Yeltsin's resignation caught opposition flat-f...,Russian roulette,Sold out,Recovering a title
1,2000-01-04,0,Scorecard,The best lake scene,Leader: German sleaze inquiry,"Cheerio, boyo",The main recommendations,Has Cubie killed fees?,Has Cubie killed fees?,Has Cubie killed fees?,...,On the critical list,The timing of their lives,Dear doctor,Irish court halts IRA man's extradition to Nor...,Burundi peace initiative fades after rebels re...,PE points the way forward to the ECB,Campaigners keep up pressure on Nazi war crime...,Jane Ratcliffe,Yet more things you wouldn't know without the ...,Millennium bug fails to bite
2,2000-01-05,0,Coventry caught on counter by Flo,United's rivals on the road to Rio,Thatcher issues defence before trial by video,Police help Smith lay down the law at Everton,Tale of Trautmann bears two more retellings,England on the rack,Pakistan retaliate with call for video of Walsh,Cullinan continues his Cape monopoly,...,South Melbourne (Australia),Necaxa (Mexico),Real Madrid (Spain),Raja Casablanca (Morocco),Corinthians (Brazil),Tony's pet project,Al Nassr (Saudi Arabia),Ideal Holmes show,Pinochet leaves hospital after tests,Useful links
3,2000-01-06,1,Pilgrim knows how to progress,Thatcher facing ban,McIlroy calls for Irish fighting spirit,Leicester bin stadium blueprint,United braced for Mexican wave,"Auntie back in fashion, even if the dress look...",Shoaib appeal goes to the top,Hussain hurt by 'shambles' but lays blame on e...,...,Putin admits Yeltsin quit to give him a head s...,BBC worst hit as digital TV begins to bite,How much can you pay for...,Christmas glitches,"Upending a table, Chopping a line and Scoring ...","Scientific evidence 'unreliable', defence claims",Fusco wins judicial review in extradition case,Rebels thwart Russian advance,Blair orders shake-up of failing NHS,Lessons of law's hard heart
4,2000-01-07,1,Hitches and Horlocks,Beckham off but United survive,Breast cancer screening,Alan Parker,Guardian readers: are you all whingers?,Hollywood Beyond,Ashes and diamonds,Whingers - a formidable minority,...,Most everywhere: UDIs,Most wanted: Chloe lunettes,Return of the cane 'completely off the agenda',From Sleepy Hollow to Greeneland,Blunkett outlines vision for over 11s,"Embattled Dobson attacks 'play now, pay later'...",Doom and the Dome,What is the north-south divide?,Aitken released from jail,Gone aloft

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4101 entries, 0 to 4100
Data columns (total 27 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    4101 non-null   object
 1   Label   4101 non-null   int64
 2   Top1    4101 non-null   object
 3   Top2    4101 non-null   object
 4   Top3    4101 non-null   object
 5   Top4    4101 non-null   object
 6   Top5    4101 non-null   object
 7   Top6    4101 non-null   object
 8   Top7    4101 non-null   object
 9   Top8    4101 non-null   object
 10  Top9    4101 non-null   object
 11  Top10   4101 non-null   object
 12  Top11   4101 non-null   object
 13  Top12   4101 non-null   object
 14  Top13   4101 non-null   object
 15  Top14   4101 non-null   object
 16  Top15   4101 non-null   object
 17  Top16   4101 non-null   object
 18  Top17   4101 non-null   object
 19  Top18   4101 non-null   object
 20  Top19   4101 non-null   object
 21  Top20   4101 non-null   object
 22  Top21   4101 non-null   object
 23  Top22   4101 non-null   object
 24  Top23   4100 non-null   object
 25  Top24   4098 non-null   object
 26  Top25   4098 non-null   object
dtypes: int64(1), object(26)
memory usage: 865.2+ KB

In [20]:
train=df[df["Date"] < "20150101"]
test=df[df["Date"] >= "20141231"]

In [22]:
# doing some feature engineering
data=train.iloc[:,2:27]
data.replace("[^a-zA-Z]", '', regex=True, inplace=True)
# renaming the columns
list1=[i for i in range(25)] 
new_index=[str(i) for i in list1]
data.columns=new_index
data.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,Ahindrancetooperationsextractsfromtheleakedrep...,Scorecard,HughesinstanthitbuoysBlues,JackgetshisskatesonaticecoldAlex,ChaosasMaracanabuildsupforUnited,DepletedLeicesterprevailasElliottspoilsEverton...,HungrySpurssenserichpickings,Gunnerssowideofaneasytarget,DerbyraiseaglasstoStruparsdebutdouble,SouthgatestrikesLeedspaythepenalty,...,FlintoffinjurypilesonwoeforEngland,HuntersthreatenJospinwithnewbattleoftheSomme,Kohlssuccessordrawnintoscandal,Thedifferencebetweenmenandwomen,SaraDenvernurseturnedsolicitor,DianaslandminecrusadeputToriesinapanic,Yeltsinsresignationcaughtoppositionflatfooted,Russianroulette,Soldout,Recoveringatitle
1,Scorecard,Thebestlakescene,LeaderGermansleazeinquiry,Cheerioboyo,Themainrecommendations,HasCubiekilledfees,HasCubiekilledfees,HasCubiekilledfees,HopkinsfuriousatFosterslackofHannibalappetite,HasCubiekilledfees,...,Onthecriticallist,Thetimingoftheirlives,Deardoctor,IrishcourthaltsIRAmansextraditiontoNorthernIre...,BurundipeaceinitiativefadesafterrebelsrejectMa...,PEpointsthewayforwardtotheECB,CampaignerskeepuppressureonNaziwarcrimessuspect,JaneRatcliffe,Yetmorethingsyouwouldntknowwithoutthemovies,Millenniumbugfailstobite
2,CoventrycaughtoncounterbyFlo,UnitedsrivalsontheroadtoRio,Thatcherissuesdefencebeforetrialbyvideo,PolicehelpSmithlaydownthelawatEverton,TaleofTrautmannbearstwomoreretellings,Englandontherack,PakistanretaliatewithcallforvideoofWalsh,CullinancontinueshisCapemonopoly,McGrathputsIndiaoutoftheirmisery,BlairWitchbandwagonrollson,...,SouthMelbourneAustralia,NecaxaMexico,RealMadridSpain,RajaCasablancaMorocco,CorinthiansBrazil,Tonyspetproject,AlNassrSaudiArabia,IdealHolmesshow,Pinochetleaveshospitalaftertests,Usefullinks
3,Pilgrimknowshowtoprogress,Thatcherfacingban,McIlroycallsforIrishfightingspirit,Leicesterbinstadiumblueprint,UnitedbracedforMexicanwave,Auntiebackinfashionevenifthedresslooksabittatty,Shoaibappealgoestothetop,Hussainhurtbyshamblesbutlaysblameonearlierdamage,Englandsdecadeofdisasters,RevengeissweetforjubilantCronje,...,PutinadmitsYeltsinquittogivehimaheadstart,BBCworsthitasdigitalTVbeginstobite,Howmuchcanyoupayfor,Christmasglitches,UpendingatableChoppingalineandScoringagoal,Scientificevidenceunreliabledefenceclaims,Fuscowinsjudicialreviewinextraditioncase,RebelsthwartRussianadvance,BlairordersshakeupoffailingNHS,Lessonsoflawshardheart
4,HitchesandHorlocks,BeckhamoffbutUnitedsurvive,Breastcancerscreening,AlanParker,Guardianreadersareyouallwhingers,HollywoodBeyond,Ashesanddiamonds,Whingersaformidableminority,AlanParkerparttwo,ThuggeryToxinsandTies,...,MosteverywhereUDIs,MostwantedChloelunettes,Returnofthecanecompletelyofftheagenda,FromSleepyHollowtoGreeneland,Blunkettoutlinesvisionforovers,EmbattledDobsonattacksplaynowpaylaterLivingstone,DoomandtheDome,Whatisthenorthsouthdivide,Aitkenreleasedfromjail,Gonealoft

In [23]:
# converting headlines to lower case
for index in data.columns:
    data[index]=data[index].str.lower()
data.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,ahindrancetooperationsextractsfromtheleakedrep...,scorecard,hughesinstanthitbuoysblues,jackgetshisskatesonaticecoldalex,chaosasmaracanabuildsupforunited,depletedleicesterprevailaselliottspoilseverton...,hungryspurssenserichpickings,gunnerssowideofaneasytarget,derbyraiseaglasstostruparsdebutdouble,southgatestrikesleedspaythepenalty,...,flintoffinjurypilesonwoeforengland,huntersthreatenjospinwithnewbattleofthesomme,kohlssuccessordrawnintoscandal,thedifferencebetweenmenandwomen,saradenvernurseturnedsolicitor,dianaslandminecrusadeputtoriesinapanic,yeltsinsresignationcaughtoppositionflatfooted,russianroulette,soldout,recoveringatitle
1,scorecard,thebestlakescene,leadergermansleazeinquiry,cheerioboyo,themainrecommendations,hascubiekilledfees,hascubiekilledfees,hascubiekilledfees,hopkinsfuriousatfosterslackofhannibalappetite,hascubiekilledfees,...,onthecriticallist,thetimingoftheirlives,deardoctor,irishcourthaltsiramansextraditiontonorthernire...,burundipeaceinitiativefadesafterrebelsrejectma...,pepointsthewayforwardtotheecb,campaignerskeepuppressureonnaziwarcrimessuspect,janeratcliffe,yetmorethingsyouwouldntknowwithoutthemovies,millenniumbugfailstobite
2,coventrycaughtoncounterbyflo,unitedsrivalsontheroadtorio,thatcherissuesdefencebeforetrialbyvideo,policehelpsmithlaydownthelawateverton,taleoftrautmannbearstwomoreretellings,englandontherack,pakistanretaliatewithcallforvideoofwalsh,cullinancontinueshiscapemonopoly,mcgrathputsindiaoutoftheirmisery,blairwitchbandwagonrollson,...,southmelbourneaustralia,necaxamexico,realmadridspain,rajacasablancamorocco,corinthiansbrazil,tonyspetproject,alnassrsaudiarabia,idealholmesshow,pinochetleaveshospitalaftertests,usefullinks
3,pilgrimknowshowtoprogress,thatcherfacingban,mcilroycallsforirishfightingspirit,leicesterbinstadiumblueprint,unitedbracedformexicanwave,auntiebackinfashionevenifthedresslooksabittatty,shoaibappealgoestothetop,hussainhurtbyshamblesbutlaysblameonearlierdamage,englandsdecadeofdisasters,revengeissweetforjubilantcronje,...,putinadmitsyeltsinquittogivehimaheadstart,bbcworsthitasdigitaltvbeginstobite,howmuchcanyoupayfor,christmasglitches,upendingatablechoppingalineandscoringagoal,scientificevidenceunreliabledefenceclaims,fuscowinsjudicialreviewinextraditioncase,rebelsthwartrussianadvance,blairordersshakeupoffailingnhs,lessonsoflawshardheart
4,hitchesandhorlocks,beckhamoffbutunitedsurvive,breastcancerscreening,alanparker,guardianreadersareyouallwhingers,hollywoodbeyond,ashesanddiamonds,whingersaformidableminority,alanparkerparttwo,thuggerytoxinsandties,...,mosteverywhereudis,mostwantedchloelunettes,returnofthecanecompletelyofftheagenda,fromsleepyhollowtogreeneland,blunkettoutlinesvisionforovers,embattleddobsonattacksplaynowpaylaterlivingstone,doomandthedome,whatisthenorthsouthdivide,aitkenreleasedfromjail,gonealoft

In [24]:
' '.join(str(x ) for x in data.iloc[1,0:25])

'scorecard thebestlakescene leadergermansleazeinquiry cheerioboyo themainrecommendations hascubiekilledfees hascubiekilledfees hascubiekilledfees hopkinsfuriousatfosterslackofhannibalappetite hascubiekilledfees ataleoftwotails isaywhatilikeandilikewhatisay elbowseyesandnipples taskforcetoassessriskofasteroidcollision howifoundmyselfatlast onthecriticallist thetimingoftheirlives deardoctor irishcourthaltsiramansextraditiontonorthernireland burundipeaceinitiativefadesafterrebelsrejectmandelaasmediator pepointsthewayforwardtotheecb campaignerskeepuppressureonnaziwarcrimessuspect janeratcliffe yetmorethingsyouwouldntknowwithoutthemovies millenniumbugfailstobite'

In [26]:
headlines=[]
for row in range(0, len(data.index)):
    headlines.append(' '.join(str(x) for x in data.iloc[row,0:25]))

In [28]:
headlines[1]

'scorecard thebestlakescene leadergermansleazeinquiry cheerioboyo themainrecommendations hascubiekilledfees hascubiekilledfees hascubiekilledfees hopkinsfuriousatfosterslackofhannibalappetite hascubiekilledfees ataleoftwotails isaywhatilikeandilikewhatisay elbowseyesandnipples taskforcetoassessriskofasteroidcollision howifoundmyselfatlast onthecriticallist thetimingoftheirlives deardoctor irishcourthaltsiramansextraditiontonorthernireland burundipeaceinitiativefadesafterrebelsrejectmandelaasmediator pepointsthewayforwardtotheecb campaignerskeepuppressureonnaziwarcrimessuspect janeratcliffe yetmorethingsyouwouldntknowwithoutthemovies millenniumbugfailstobite'

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier

In [30]:
countvector=CountVectorizer(ngram_range=(2,2))
traindataset=countvector.fit_transform(headlines)

In [31]:
randomclassifier=RandomForestClassifier(n_estimators=200, random_state=0,criterion='entropy')
randomclassifier.fit(traindataset,train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=0)

In [34]:
# predict the test set
testdata=test.iloc[:,2:27]
testdata.replace("[^a-zA-Z]", '', regex=True, inplace=True)
testdata.columns=new_index  
for index in testdata.columns:
    testdata[index]=testdata[index].str.lower()
testheadlines=[]
for row in range(0, len(testdata.index)):
    testheadlines.append(' '.join(str(x) for x in testdata.iloc[row,0:25]))
testheadlines[1]
testdataset=countvector.transform(testheadlines)
predictions=randomclassifier.predict(testdataset)
predictions[1]

0

In [36]:
import sklearn
from sklearn.metrics import confusion_matrix
sklearn.metrics.confusion_matrix(test['Label'], predictions)
from sklearn.metrics import classification_report
print(classification_report(test['Label'], predictions))
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(test['Label'], predictions)
print(accuracy)

              precision    recall  f1-score   support

           0       1.00      0.70      0.82       186
           1       0.77      1.00      0.87       192

    accuracy                           0.85       378
   macro avg       0.89      0.85      0.85       378
weighted avg       0.89      0.85      0.85       378

0.8518518518518519